# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import et_service_pb2 as et__service__pb2


class ETServiceStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.loginWithGoogle = channel.unary_unary(
            '/ETService/loginWithGoogle',
            request_serializer=et__service__pb2.LoginWithGoogle.Request.SerializeToString,
            response_deserializer=et__service__pb2.LoginWithGoogle.Response.FromString,
        )
        self.loginDashboard = channel.unary_unary(
            '/ETService/loginDashboard',
            request_serializer=et__service__pb2.LoginDashboard.Request.SerializeToString,
            response_deserializer=et__service__pb2.LoginDashboard.Response.FromString,
        )
        self.bindUserToCampaign = channel.unary_unary(
            '/ETService/bindUserToCampaign',
            request_serializer=et__service__pb2.BindUserToCampaign.Request.SerializeToString,
            response_deserializer=et__service__pb2.BindUserToCampaign.Response.FromString,
        )
        self.retrieveParticipants = channel.unary_unary(
            '/ETService/retrieveParticipants',
            request_serializer=et__service__pb2.RetrieveParticipants.Request.SerializeToString,
            response_deserializer=et__service__pb2.RetrieveParticipants.Response.FromString,
        )
        self.retrieveParticipantStats = channel.unary_unary(
            '/ETService/retrieveParticipantStats',
            request_serializer=et__service__pb2.RetrieveParticipantStats.Request.SerializeToString,
            response_deserializer=et__service__pb2.RetrieveParticipantStats.Response.FromString,
        )
        self.registerCampaign = channel.unary_unary(
            '/ETService/registerCampaign',
            request_serializer=et__service__pb2.RegisterCampaign.Request.SerializeToString,
            response_deserializer=et__service__pb2.RegisterCampaign.Response.FromString,
        )
        self.deleteCampaign = channel.unary_unary(
            '/ETService/deleteCampaign',
            request_serializer=et__service__pb2.DeleteCampaign.Request.SerializeToString,
            response_deserializer=et__service__pb2.DeleteCampaign.Response.FromString,
        )
        self.retrieveCampaigns = channel.unary_unary(
            '/ETService/retrieveCampaigns',
            request_serializer=et__service__pb2.RetrieveCampaigns.Request.SerializeToString,
            response_deserializer=et__service__pb2.RetrieveCampaigns.Response.FromString,
        )
        self.retrieveCampaign = channel.unary_unary(
            '/ETService/retrieveCampaign',
            request_serializer=et__service__pb2.RetrieveCampaign.Request.SerializeToString,
            response_deserializer=et__service__pb2.RetrieveCampaign.Response.FromString,
        )
        self.bindDataSource = channel.unary_unary(
            '/ETService/bindDataSource',
            request_serializer=et__service__pb2.BindDataSource.Request.SerializeToString,
            response_deserializer=et__service__pb2.BindDataSource.Response.FromString,
        )
        self.retrieveDataSources = channel.unary_unary(
            '/ETService/retrieveDataSources',
            request_serializer=et__service__pb2.RetrieveDataSources.Request.SerializeToString,
            response_deserializer=et__service__pb2.RetrieveDataSources.Response.FromString,
        )
        self.submitDataRecord = channel.unary_unary(
            '/ETService/submitDataRecord',
            request_serializer=et__service__pb2.SubmitDataRecord.Request.SerializeToString,
            response_deserializer=et__service__pb2.SubmitDataRecord.Response.FromString,
        )
        self.submitDataRecords = channel.unary_unary(
            '/ETService/submitDataRecords',
            request_serializer=et__service__pb2.SubmitDataRecords.Request.SerializeToString,
            response_deserializer=et__service__pb2.SubmitDataRecords.Response.FromString,
        )
        self.retrieve100DataRecords = channel.unary_unary(
            '/ETService/retrieve100DataRecords',
            request_serializer=et__service__pb2.Retrieve100DataRecords.Request.SerializeToString,
            response_deserializer=et__service__pb2.Retrieve100DataRecords.Response.FromString,
        )
        self.retrieveFilteredDataRecords = channel.unary_unary(
            '/ETService/retrieveFilteredDataRecords',
            request_serializer=et__service__pb2.RetrieveFilteredDataRecords.Request.SerializeToString,
            response_deserializer=et__service__pb2.RetrieveFilteredDataRecords.Response.FromString,
        )
        self.submitHeartbeat = channel.unary_unary(
            '/ETService/submitHeartbeat',
            request_serializer=et__service__pb2.SubmitHeartbeat.Request.SerializeToString,
            response_deserializer=et__service__pb2.SubmitHeartbeat.Response.FromString,
        )
        self.submitDirectMessage = channel.unary_unary(
            '/ETService/submitDirectMessage',
            request_serializer=et__service__pb2.SubmitDirectMessage.Request.SerializeToString,
            response_deserializer=et__service__pb2.SubmitDirectMessage.Response.FromString,
        )
        self.retrieveUnreadDirectMessages = channel.unary_unary(
            '/ETService/retrieveUnreadDirectMessages',
            request_serializer=et__service__pb2.RetrieveUnreadDirectMessages.Request.SerializeToString,
            response_deserializer=et__service__pb2.RetrieveUnreadDirectMessages.Response.FromString,
        )
        self.retrieveUnreadNotifications = channel.unary_unary(
            '/ETService/retrieveUnreadNotifications',
            request_serializer=et__service__pb2.RetrieveUnreadNotifications.Request.SerializeToString,
            response_deserializer=et__service__pb2.RetrieveUnreadNotifications.Response.FromString,
        )


class ETServiceServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def loginWithGoogle(self, request, context):
        """user management module
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def loginDashboard(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def bindUserToCampaign(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def retrieveParticipants(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def retrieveParticipantStats(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def registerCampaign(self, request, context):
        """campaign management module
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteCampaign(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def retrieveCampaigns(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def retrieveCampaign(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def bindDataSource(self, request, context):
        """data source management module
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def retrieveDataSources(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def submitDataRecord(self, request, context):
        """data management module
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def submitDataRecords(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def retrieve100DataRecords(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def retrieveFilteredDataRecords(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def submitHeartbeat(self, request, context):
        """statistics module
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def submitDirectMessage(self, request, context):
        """communication management module
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def retrieveUnreadDirectMessages(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def retrieveUnreadNotifications(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ETServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'loginWithGoogle': grpc.unary_unary_rpc_method_handler(
            servicer.loginWithGoogle,
            request_deserializer=et__service__pb2.LoginWithGoogle.Request.FromString,
            response_serializer=et__service__pb2.LoginWithGoogle.Response.SerializeToString,
        ),
        'loginDashboard': grpc.unary_unary_rpc_method_handler(
            servicer.loginDashboard,
            request_deserializer=et__service__pb2.LoginDashboard.Request.FromString,
            response_serializer=et__service__pb2.LoginDashboard.Response.SerializeToString,
        ),
        'bindUserToCampaign': grpc.unary_unary_rpc_method_handler(
            servicer.bindUserToCampaign,
            request_deserializer=et__service__pb2.BindUserToCampaign.Request.FromString,
            response_serializer=et__service__pb2.BindUserToCampaign.Response.SerializeToString,
        ),
        'retrieveParticipants': grpc.unary_unary_rpc_method_handler(
            servicer.retrieveParticipants,
            request_deserializer=et__service__pb2.RetrieveParticipants.Request.FromString,
            response_serializer=et__service__pb2.RetrieveParticipants.Response.SerializeToString,
        ),
        'retrieveParticipantStats': grpc.unary_unary_rpc_method_handler(
            servicer.retrieveParticipantStats,
            request_deserializer=et__service__pb2.RetrieveParticipantStats.Request.FromString,
            response_serializer=et__service__pb2.RetrieveParticipantStats.Response.SerializeToString,
        ),
        'registerCampaign': grpc.unary_unary_rpc_method_handler(
            servicer.registerCampaign,
            request_deserializer=et__service__pb2.RegisterCampaign.Request.FromString,
            response_serializer=et__service__pb2.RegisterCampaign.Response.SerializeToString,
        ),
        'deleteCampaign': grpc.unary_unary_rpc_method_handler(
            servicer.deleteCampaign,
            request_deserializer=et__service__pb2.DeleteCampaign.Request.FromString,
            response_serializer=et__service__pb2.DeleteCampaign.Response.SerializeToString,
        ),
        'retrieveCampaigns': grpc.unary_unary_rpc_method_handler(
            servicer.retrieveCampaigns,
            request_deserializer=et__service__pb2.RetrieveCampaigns.Request.FromString,
            response_serializer=et__service__pb2.RetrieveCampaigns.Response.SerializeToString,
        ),
        'retrieveCampaign': grpc.unary_unary_rpc_method_handler(
            servicer.retrieveCampaign,
            request_deserializer=et__service__pb2.RetrieveCampaign.Request.FromString,
            response_serializer=et__service__pb2.RetrieveCampaign.Response.SerializeToString,
        ),
        'bindDataSource': grpc.unary_unary_rpc_method_handler(
            servicer.bindDataSource,
            request_deserializer=et__service__pb2.BindDataSource.Request.FromString,
            response_serializer=et__service__pb2.BindDataSource.Response.SerializeToString,
        ),
        'retrieveDataSources': grpc.unary_unary_rpc_method_handler(
            servicer.retrieveDataSources,
            request_deserializer=et__service__pb2.RetrieveDataSources.Request.FromString,
            response_serializer=et__service__pb2.RetrieveDataSources.Response.SerializeToString,
        ),
        'submitDataRecord': grpc.unary_unary_rpc_method_handler(
            servicer.submitDataRecord,
            request_deserializer=et__service__pb2.SubmitDataRecord.Request.FromString,
            response_serializer=et__service__pb2.SubmitDataRecord.Response.SerializeToString,
        ),
        'submitDataRecords': grpc.unary_unary_rpc_method_handler(
            servicer.submitDataRecords,
            request_deserializer=et__service__pb2.SubmitDataRecords.Request.FromString,
            response_serializer=et__service__pb2.SubmitDataRecords.Response.SerializeToString,
        ),
        'retrieve100DataRecords': grpc.unary_unary_rpc_method_handler(
            servicer.retrieve100DataRecords,
            request_deserializer=et__service__pb2.Retrieve100DataRecords.Request.FromString,
            response_serializer=et__service__pb2.Retrieve100DataRecords.Response.SerializeToString,
        ),
        'retrieveFilteredDataRecords': grpc.unary_unary_rpc_method_handler(
            servicer.retrieveFilteredDataRecords,
            request_deserializer=et__service__pb2.RetrieveFilteredDataRecords.Request.FromString,
            response_serializer=et__service__pb2.RetrieveFilteredDataRecords.Response.SerializeToString,
        ),
        'submitHeartbeat': grpc.unary_unary_rpc_method_handler(
            servicer.submitHeartbeat,
            request_deserializer=et__service__pb2.SubmitHeartbeat.Request.FromString,
            response_serializer=et__service__pb2.SubmitHeartbeat.Response.SerializeToString,
        ),
        'submitDirectMessage': grpc.unary_unary_rpc_method_handler(
            servicer.submitDirectMessage,
            request_deserializer=et__service__pb2.SubmitDirectMessage.Request.FromString,
            response_serializer=et__service__pb2.SubmitDirectMessage.Response.SerializeToString,
        ),
        'retrieveUnreadDirectMessages': grpc.unary_unary_rpc_method_handler(
            servicer.retrieveUnreadDirectMessages,
            request_deserializer=et__service__pb2.RetrieveUnreadDirectMessages.Request.FromString,
            response_serializer=et__service__pb2.RetrieveUnreadDirectMessages.Response.SerializeToString,
        ),
        'retrieveUnreadNotifications': grpc.unary_unary_rpc_method_handler(
            servicer.retrieveUnreadNotifications,
            request_deserializer=et__service__pb2.RetrieveUnreadNotifications.Request.FromString,
            response_serializer=et__service__pb2.RetrieveUnreadNotifications.Response.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'ETService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
