# Generated by Django 2.2.12 on 2020-06-18 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField()),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 18, 16, 16, 49, 751904))),
                ('day_num', models.IntegerField(default=0)),
                ('ema_order', models.SmallIntegerField(default=0)),
                ('prediction_result', models.SmallIntegerField(default=-1)),
                ('accuracy', models.SmallIntegerField(default=0)),
                ('feature_ids', models.TextField()),
                ('model_tag', models.BooleanField(default=False)),
                ('user_tag', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('uid', 'day_num', 'ema_order', 'prediction_result')},
            },
        ),
    ]
