# Generated by Django 2.2.12 on 2020-07-24 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_service', '0003_auto_20200618_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelresult',
            name='accuracy',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='modelresult',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 24, 19, 42, 14, 698888)),
        ),
    ]
